[versions]
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
leanback = "1.2.0"
lifecycle = "2.10.0"
palette = "1.0.0"
glide = "4.16.0"
guava = "33.4.8-jre"
gson = "2.13.1"
material = "1.12.0"
localWeather = "2.0"
kotlinxCoroutines = "1.10.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
androidx-leanback-preference = { group = "androidx.leanback", name = "leanback-preference", version.ref = "leanback" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }

google-guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

local-weather = { group = "com.github.interaapps", name = "LocalWeather-Android", version.ref = "localWeather" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
